main: online.starsmc.simplesetspawn.Main
name: SimpleSetSpawn

version:  1.2.1
api-version: 1.13
description: Spawn plugin for 1.8 to Latest version

folia-supported: true

softdepend:
  - PlaceholderAPI